[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/zips/*"
  to = "/.netlify/functions/serve-zip/:splat"
  status = 200

[dev]
  framework = "#static"
  targetPort = 3000
