[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install && npm run build"

# Remove the [[plugins]] section completely - no need for it
# Netlify handles Git LFS internally

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/uploads/*"
  to = "/public/uploads/:splat"
  status = 200

[[redirects]]
  from = "/zips/*"
  to = "/public/zips/:splat"
  status = 200
